version: '3.8'

services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - my_network

  mysql-client:
    image: mysql:latest
    container_name: mysql-client
    entrypoint: ["bash"]
    networks:
      - my_network
    stdin_open: true
    tty: true

networks:
  my_network:
    driver: bridge
