version: '3.8'

services:
  mysql-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-server
    networks:
      - my_network

  mysql-client:
    image: mysql:latest
    container_name: mysql-client
    entrypoint: ["bash"]
    networks:
      - my_network
    stdin_open: true
    tty: true

networks:
  my_network:
    driver: bridge
