---
- name: Day Two Start Settings
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Set the PS1 Prompt
      lineinfile:
        path: ~/.bashrc
        regexp: "^export PS1="
        line: export PS1="\u@ubuntu \w \$ "
        insertafter: EOF
    - name: Add sudoers entry for labadmin user account
      become: true
      copy:
        dest: /etc/sudoers.d/labadmin
        content: 'labadmin ALL=(root) NOPASSWD: ALL'
        validate: visudo -cf %s
    - name: Install Pycharm
      become: true
      snap:
        name: pycharm-community
        classic: true
    - name: Create Config for Ansible
      copy:
        dest: ~/.ansible.cfg
        content: |
          [defaults]
          host_key_checking = false
    - name: Create Sample Ansible Inventory
      copy:
        dest: ~/hosts.ini
        content: |
          [ubuntu]
          localhost
          [rocky]
          rocky1
          rocky2
