---
- name: Manage SSH Connection to System
  hosts: localhost
  become: true
  gather_facts: false
  tasks:

    - name: Install Fail2Ban Firewall Manager
      package:
        name: fail2ban

    - name: Create Jail to Block Bad Logins
      template:
        dest: /etc/fail2ban/jail.d/sshd.conf
        src: sshd.conf.j2
      notify: restart fail2ban

  handlers:
    - name: restart fail2ban
      service:
        name: fail2ban
        state: restarted

