---
- name: Clear Docker Install From Ubuntu
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Uninstall packages from Ubuntu repo
      pkg:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - containerd
          - runc

    - name: Ensure directories are removed

    - name: Remove /var/lib/docker directory
      file:
        path: /var/lib/docker
        state: absent

    - name: Remove /var/lib/containerd directory
      file:
        path: /var/lib/containerd
        state: absent

