---
- name: Clear Docker Install From Ubuntu
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Uninstall packages from Ubuntu repo
      pkg:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - containerd


 for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done



 sudo rm -rf /var/lib/docker
 sudo rm -rf /var/lib/containerd
